---
# This role will install redis in group 'redis' in the environment inventory
# In deploy mode it will deploy redis.
# In clean mode it will remove the redis containers.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"

