---
# This role will prepare target VMs for a whisk deployment using ansible.
# In deploy mode it will install all necessary packages and programs.
# In clean mode it will uninstall packages from deploy mode.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
