---
# Remove consul agent/server and registrator containers as well as the consul.confdir

- name: remove registrator
  docker_container:
    name: registrator
    image: "gliderlabs/registrator"
    state: absent
  ignore_errors: True

- name: remove consul
  docker_container:
    name: consul
    image: "{{ docker_registry }}{{ docker.image.prefix }}/consul:{{ docker.image.tag }}"
    state: absent
  ignore_errors: True

- name: remove consul config directory
  file:
    path: "{{ consul.confdir }}"
    state: absent
  become: true

- name: remove consul log directory
  file:
    path: "{{ whisk_logs_dir }}/consul"
    state: absent
  become: true

- name: remove registrator log directory
  file:
    path: "{{ whisk_logs_dir }}/registrator"
    state: absent
  become: true
