---

# Copy the cli binaries to Nginx directory

- name: "construct local file from which to source"
  set_fact:
    source_file: "{{ openwhisk_cli.local.location }}/\
      {{ item | join('-') | replace('mac','darwin') }}/\
      {{ (item[0] == 'windows') | ternary ('wsk.exe', 'wsk') }}"
    target_dir: "{{ cli.nginxdir }}/{{ item[0] }}/{{ item[1] }}"
    system_match: "{{ ( \
        (ansible_system == 'Linux' and item[0] == 'linux') \
        or (ansible_system == 'Darwin' and item[0] == 'mac') \
        or (ansible_system == 'Windows' and item[0] == 'windows') \
        ) }}"
    arch_match: "{{ ( ((ansible_machine=='x86_64')|ternary('amd64', ansible_machine)) == item[1] ) }}"

- local_action: stat path={{ source_file }}
  register: binary_path

- name: "ensure Nginx cli directory is writable"
  file:
    path: "{{ target_dir }}"
    state: directory
    mode: 0777
  become: "{{ cli.dir.become }}"

- name: "copy the local binaries from a local directory to Nginx directory"
  copy:
    src: "{{ source_file }}"
    dest: "{{ target_dir }}/"
  when: binary_path.stat.exists

- name: "copy the local binary to the root bin directory when architectures match"
  local_action: copy src={{ source_file }} dest={{ openwhisk_home }}/bin mode=0755
  when: system_match and arch_match
