sudo: required
language: java
services:
  - docker

env:
  - TERM=dumb

install:
  - ./preparation/deploy.sh

script:
  - ./wrk_tests/latency.sh "http://172.17.0.1:10001" "$(cat openwhisk/ansible/files/auth.guest)" 2m
  - ./wrk_tests/throughput.sh "http://172.17.0.1:10001" "$(cat openwhisk/ansible/files/auth.guest)" 4 2 2m
