---
# This role will install nginx.
# In deploy mode it will deploy an nginx server.
# In clean mode it will remove the nginx server as well as nginx.confdir

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
