---
# This playbook installs additional packages after whisk has been deployed.

- import_playbook: properties.yml

- hosts: ansible
  tasks:
    - include_tasks: tasks/installOpenwhiskCatalog.yml
      when: (mode == "deploy")
      with_dict: "{{ catalog_repos }}"
